# Generated by Django 5.2.4 on 2025-08-19 06:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default=None, max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('product_stock', models.PositiveBigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('product_image', models.ImageField(default=None, upload_to='products_images')),
                ('product_category', models.CharField(default=None, max_length=255)),
                ('product_description', models.TextField(default=None)),
                ('product_created_at', models.DateTimeField(auto_now_add=True)),
                ('product_updated_at', models.DateTimeField(auto_now=True)),
                ('product_seller_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
